services:
  app:
    container_name: app
    build: .
    ports:
      - 8000:8000
    working_dir: /code
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - rabbitmq
      - postgres

  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data:cached

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - app

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A scraping worker -l INFO
    env_file: .env
    depends_on:
      - rabbitmq
      - app
      - postgres
    links:
      - rabbitmq

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A scraping beat -l INFO
    env_file: .env
    depends_on:
      - rabbitmq
      - app
      - postgres
    links:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"


volumes:
  postgres_data: