services:
  app:
    container_name: app
    build: .
    ports:
      - 8000:8000
    working_dir: /code
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - rabbitmq

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - 80:80
    depends_on:
      - app

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A scraping worker -l INFO
    env_file: .env
    depends_on:
      - rabbitmq
      - app
    links:
      - rabbitmq

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A scraping beat -l INFO
    env_file: .env
    depends_on:
      - rabbitmq
      - app
    links:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
