# Generated by Django 4.1.7 on 2023-03-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Parsed/created at"),
        ),
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.CharField(default="", max_length=2083, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="news",
            name="published",
            field=models.DateTimeField(verbose_name="Published at"),
        ),
        migrations.AlterField(
            model_name="news",
            name="source",
            field=models.CharField(blank=True, default="", max_length=30, null=True, verbose_name="Source"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
